package com.marketintel.model;

public enum ActionType {

    MARKET_QUOTE,
    SECURITY_OVERVIEW,

    ETF_SECTOR_EXPOSURE,
    ETF_GEOGRAPHIC_EXPOSURE,
    SECURITY_COMPARISON,
    ETF_OVERLAP,
    FINANCIAL_NEWS,

    PORTFOLIO_VIEW,
    PORTFOLIO_ADD,
    PORTFOLIO_REMOVE,
    PORTFOLIO_EXPOSURE,

    WATCHLIST_VIEW,
    WATCHLIST_ADD,
    WATCHLIST_REMOVE
}